config/routes.rb
Dfrpg::Application.routes.draw do

  resources :characters, :only => [:index, :show]
  resources :users, :controller => 'clearance/users' do
    resources :characters
  end

  root :to => 'characters#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
  attr_accessible :adjusted_refresh, :armor_misc, :background, :background_phase_aspect, :base_refresh, :consequences, :current_fate_points, :fp_from_last_session, :guest_star, :guest_star_phase_aspect, :guest_star_redux, :guest_star_redux_phase_aspect, :high_concept_aspect, :mental_stress, :musts, :name, :other_aspects, :physical_stress, :player, :power_level, :rising_conflict, :rising_conflict_phase_aspect, :skill_cap, :skill_points, :skills, :social_stress, :stunts_and_powers, :template, :the_story, :the_story_phase_aspect, :total_available, :total_refresh_adjustment, :trouble_aspect

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  respond_to :html, :json
  before_filter :authorize, :only => [:new, :create, :destroy, :update, :edit]
  before_filter :verify_ownership, :only => [:edit, :update, :destroy]

  expose(:character)
  expose(:characters) { Character.all }

  def create
    character.user_id = current_user.id
    if character.save
      respond_with character
    else
      render :new
    end
  end

  def update
    character.user_id = current_user.id
    if character.save
      respond_with character
    else
      render :edit
    end
  end

  private

  def verify_ownership
    if current_user != character.user
      raise ActiveRecord::RecordNotFound
    end
    character
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/_form.html.haml
%section#character_info
  #page-title
    %h3 The Dresden Files Role-Playing Game
    %h1 Character Sheet
  = simple_form_for character, :url => user_characters_path do |f|
    #character-info
      #character
        = f.input :name
      #player
        = f.input :player
    #aspects
      = f.input :high_concept_aspect
      = f.input :trouble_aspect
      = f.input :other_aspects
    #skills
      = f.input :skills
    #stress
      = f.input :physical_stress
      = f.input :mental_stress
      = f.input :social_stress
      = f.input :armor_misc, :as => "string"
    #consequences
      = f.input :consequences
    #current_status
      = f.input :power_level
      = f.input :skill_cap
      = f.input :skill_points
      = f.input :total_available
      = f.input :base_refresh
      = f.input :adjusted_refresh
      = f.input :fp_from_last_session
      = f.input :current_fate_points
    #stunts_and_powers
      = f.input :stunts_and_powers
    #phase_one
      = f.input :background
      = f.input :background_phase_aspect
    #phase_two
      = f.input :rising_conflict
      = f.input :rising_conflict_phase_aspect
    #phase_three
      = f.input :the_story
      = f.input :the_story_phase_aspect
    #phase_four
      = f.input :guest_star
      = f.input :guest_star_phase_aspect
    #phase_five
      = f.input :guest_star_redux
      = f.input :guest_star_redux_phase_aspect
    = f.button :submit

app/views/characters/edit.html.haml
= render :partial => "form"

app/views/characters/index.html.haml
%h1.title List of Dresden Characters 
#actions
  - if signed_in?
    = link_to("Create a New Character", new_user_character_path(current_user.id), :class => "button", :id => "new_character_button")
%section#characters-list
  %section#all-characters
    %h4 Characters
    %table
      %thead
        %th Name
        %th High Concept 
        %th Player
      %tbody
        - if  characters
          -  characters.each do |character|
            %tr
              %td
                = link_to("#{character.name}", character_path(character))
              %td
                = character.high_concept_aspect
              %td
                = character.player

  - if signed_in? && current_user.characters.any?
    %section#your-characters
      %h4 Your Characters
      %table
        %thead
          %th Name
          %th High Concept 
          %th Player
        %tbody
          - current_user.characters.each do |character|
            %tr
              %td
                = link_to("#{character.name}", character_path(character))
              %td
                = character.high_concept_aspect
              %td
                = character.player

app/views/characters/new.html.haml
= render :partial => "form"

app/views/characters/show.html.haml
%section#character_info
  #page-title
    %h3 The Dresden Files Role-Playing Game
    %h1 Character Sheet
  #character-info

    #character
      %label Name
      %p=  character.name
    #player
      %label Player
      %p=  character.player

  #aspects
    %label Aspects
    %label High Concept
    %p=  character.high_concept_aspect
    %label Trouble
    %p=  character.trouble_aspect
    %label Other Aspects
    %p=  character.other_aspects
  #skills
    %label Skills
    %p=  character.skills
  #stress
    %label Stress
    %label Physical
    %p=  character.physical_stress
    %label Mental
    %p=  character.mental_stress
    %label Social
    %p=  character.social_stress
    %label Armor, ETC:
    %p=  character.armor_misc
    
  #consequences
    %label Consequences
    %p=  character.consequences
  #current_status
    %label Power Level
    %p=  character.power_level
    %label Skill Cap
    %p=  character.skill_cap
    %label Skill Points
    %p=  character.skill_points
    %label Total Available
    %p=  character.total_available
    %label Base Refresh
    %p=  character.base_refresh
    %label Adjusted Refresh
    %p=  character.adjusted_refresh
    %label FP from last session
    %p=  character.fp_from_last_session
    %label Current Fate Points
    %p=  character.current_fate_points
  #stunts_and_powers
    %label Stunts and Powers
    %p=  character.stunts_and_powers
  #phase_one
    %label Phase one
    %label Background
    %p= character.background
    %label Phase Aspect
    %p= character.background_phase_aspect
  #phase_two
    %label Phase two
    %label Rising Conflict
    %p=  character.rising_conflict
    %label Phase Aspect
    %p=  character.rising_conflict_phase_aspect
  #phase_three
    %label Phase three
    %label The Story
    %p=  character.the_story
    %label Phase Aspect
    %p=  character.the_story_phase_aspect
  #phase_four
    %label Phase four
    %label Guest Star
    %p=  character.guest_star
    %label Phase Aspect
    %p=  character.guest_star_phase_aspect
  #phase_five
    %label Phase five
    %label Guest Star Redux
    %p=  character.guest_star_redux
    %label Phase Aspect
    %p=  character.guest_star_redux_phase_aspect

  - if signed_in? && current_user == character.user
    = link_to("Edit Character", edit_user_character_path(current_user.id), :class => "button", :id => "edit_character_button")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Dfrpg
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag  "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    %header
      %ul#navigation
        %li 
          = link_to("Home", root_path)
        %li
          = signed_in? ? link_to("Sign Out", sign_out_path, :method => :delete) : link_to("Sign in", sign_in_path)

    = yield